name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}      
    - name: Install dependencies
      with:
        env:
          MOD_USER_CHANNEL_ID  :  ${{ secret.MOD_USER_CHANNEL_ID }} 
          MY_CHANNEL_ID        :  ${{ secret.MY_CHANNEL_ID      }}
          TOBOR_ACCESS_TOKEN   :  ${{ secret.TOBOR_ACCESS_TOKEN }}
          TOBOR_CLIENT_ID      :  ${{ secret.TOBOR_CLIENT_ID    }}
          TOBOR_REFRESH_TOKEN  :  ${{ secret.TOBOR_REFRESH_TOKEN }}
          TOBOR_USER_TOKEN     :  ${{ secret.TOBOR_USER_TOKEN   }}

      run: |
        python -m pip install --upgrade pip
        pip install '.[dev]'
    - name: Running tests
      run: |
        ./scripts/test.sh credentials
