name: Version

on:
  push:
    paths-ignore:
      - 'scripts/VERSION'
    branches:
      - main
    permissions:
      contents: read
      issues: write
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Version code
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[dev]'
    - name: Update patch version
      run: |
        ./scripts/update.py git-version patch 
    - name: Git add and tag code
      run: |
        export VERSION=$(cat git-version)
        export MESSAGE=$(git log -1 --pretty=%B)
        export AUTHOR=$(cat scripts/AUTHOR)
        export AUTHOR_EMAIL=$(cat scripts/AUTHOR_EMAIL)
        git config --global user.name ${AUTHOR}
        git config --global user.email ${AUTHOR_EMAIL}
        git add git-version
        git commit -am "Up version ${VERSION}"
        git tag -a "v${VERSION}" -m "${MESSAGE}"
        git push origin main
        git push origin tag "v${VERSION}"
         
